language: java
jdk:
  - openjdk11
branches:
  only:
    - master

#Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"
before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r springboot-webservice *
  - mkdir -p deploy
  - mv springboot-webservice.zip deploy/springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: AKIARSAFZKF6RD7AIYVO
    secret_access_key: 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
    bucket: kjm-springboot-study-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: AKIARSAFZKF6RD7AIYVO
    secret_access_key: 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
    bucket: kjm-springboot-study-build
    key: springboot-webservice.zip
    build_type: zip
    application: springboot-study-webservice
    deployment_group: springboot-study-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true

#CI 실행 완료시 메일로 알려주자  아디  비
notifications:
  email:
    recipients:
      - kimth5533@naver.com
