language: java
jdk:
  - openjdk11
before_install:
  - chomod +x gradlew
branches:
  only:
    - master

#Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

#CI 실행 완료시 메일로 알려주자
notifications:
  email:
    recipients:
      - kimth5533@naver.com